brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
namesrvAddr = rocketmq-namesrv:9876
brokerIP1 = 192.168.6.222
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog
storePathConsumeQueue = /home/rocketmq/store/consumequeue
storePathIndex = /home/rocketmq/store/index
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true
